
// Auto-generated utility for accessing WebP images
// This file is auto-generated by the convert-images script. Do not edit manually.

/**
 * Gets the WebP version of an image path
 * @param originalPath The original image path (jpg, png)
 * @returns The WebP image path or the original if no WebP conversion exists
 */
export function getWebPPath(originalPath: string): string {
  // Import JSON using dynamic import for ESM compatibility
  const mapping = JSON.parse(fs.readFileSync(new URL('./image-mappings.json', import.meta.url), 'utf-8'));
  
  // Handle paths with or without leading slash
  const normalizedPath = originalPath.startsWith('/')
    ? originalPath.substring(1)
    : originalPath;
  
  return mapping[normalizedPath] || originalPath;
}
  