// Auto-generated utility for accessing WebP images
// This file is auto-generated by the convert-images script. Do not edit manually.

import imageMappings from './image-mappings.json';

/**
 * Gets the WebP version of an image path
 * @param originalPath The original image path (jpg, png)
 * @returns The WebP image path or the original if no WebP conversion exists
 */
export function getWebPPath(originalPath: string): string {
  // Handle paths with or without leading slash
  const normalizedPath = originalPath.startsWith('/')
    ? originalPath.substring(1)
    : originalPath;
  
  return (imageMappings as Record<string, string>)[normalizedPath] || originalPath;
}
  