[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "http://polsterei-hb-zuerich.ch/*"
  to = "https://polsterei-hb-zuerich.ch/:splat"
  status = 301
  force = true

# Default language redirect
[[redirects]]
  from = "/"
  to = "/de/"
  status = 301
  force = true

# Handle form submissions and success pages
[[redirects]]
  from = "/de/success"
  to = "/de/"
  status = 200

[[redirects]]
  from = "/en/success"
  to = "/en/"
  status = 200

# SPA fallback - this ensures React handles all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[dev]
  framework = "vite"

# Enable form detection
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.forms]
  enabled = true