import fs from 'fs';
import path from 'path';
import sharp from 'sharp';
import { globSync } from 'glob';
import { fileURLToPath } from 'url';

// Get directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Quality settings for different image types
const WEBP_QUALITY = {
  hero: 80,
  background: 75, 
  portfolio: 85,
  service: 80,
  default: 80
};

// Source image directory
const PUBLIC_DIR = path.resolve(__dirname, '../public');
const IMAGE_DIRS = [
  path.join(PUBLIC_DIR, 'images'),
  path.join(PUBLIC_DIR, 'images/hero'),
  path.join(PUBLIC_DIR, 'images/hero/fallback'),
  path.join(PUBLIC_DIR, 'images/portfolio'),
  path.join(PUBLIC_DIR, 'images/services'),
];

// Target directories for WebP images
const WEBP_DIRS = {
  'images/hero/fallback': 'images/hero',
  'images': 'images',
  'images/hero': 'images/hero',
  'images/portfolio': 'images/portfolio',
  'images/services': 'images/services',
};

// Make sure WebP directories exist
for (const dir of Object.values(WEBP_DIRS)) {
  const fullDir = path.join(PUBLIC_DIR, dir);
  if (!fs.existsSync(fullDir)) {
    fs.mkdirSync(fullDir, { recursive: true });
  }
}

// Find all image files
async function findImages() {
  const imageFiles = [];
  
  for (const dir of IMAGE_DIRS) {
    if (fs.existsSync(dir)) {
      const files = globSync(path.join(dir, '**/*.{jpg,jpeg,png}'));
      imageFiles.push(...files);
    }
  }
  
  return imageFiles;
}

// Convert image to WebP
async function convertImage(imagePath) {
  try {
    const relativePath = path.relative(PUBLIC_DIR, imagePath);
    const relativeDir = path.dirname(relativePath);
    const targetDir = WEBP_DIRS[relativeDir] || path.dirname(relativePath);
    
    // Calculate quality based on image path
    let quality = WEBP_QUALITY.default;
    if (imagePath.includes('hero')) quality = WEBP_QUALITY.hero;
    else if (imagePath.includes('background')) quality = WEBP_QUALITY.background;
    else if (imagePath.includes('portfolio')) quality = WEBP_QUALITY.portfolio;
    else if (imagePath.includes('service')) quality = WEBP_QUALITY.service;
    
    // Find image size category (small, medium, large)
    let sizeSuffix = '';
    if (imagePath.includes('-small')) sizeSuffix = '-small';
    else if (imagePath.includes('-medium')) sizeSuffix = '-medium';
    else if (imagePath.includes('-large')) sizeSuffix = '-large';
    
    // Remove the size suffix from the base filename
    const filename = path.basename(imagePath, path.extname(imagePath))
      .replace(/-small$/, '')
      .replace(/-medium$/, '')
      .replace(/-large$/, '');
    
    // Create target WebP filename with appropriate size suffix
    const webpFilename = `${filename}${sizeSuffix}.webp`;
    const outputPath = path.join(PUBLIC_DIR, targetDir, webpFilename);
    
    // Skip if WebP already exists
    if (fs.existsSync(outputPath)) {
      console.log(`Skipping existing: ${webpFilename}`);
      return {
        originalPath: relativePath,
        webpPath: path.join(targetDir, webpFilename).replace(/\\/g, '/'),
        exists: true
      };
    }
    
    // Optimize and convert to WebP
    await sharp(imagePath)
      .webp({ quality })
      .toFile(outputPath);
    
    console.log(`Converted: ${relativePath} → ${path.join(targetDir, webpFilename)}`);
    
    return {
      originalPath: relativePath,
      webpPath: path.join(targetDir, webpFilename).replace(/\\/g, '/'),
      exists: false
    };
  } catch (err) {
    console.error(`Error converting ${imagePath}:`, err);
    return null;
  }
}

// Generate mapping file for easy reference
function generateMappingFile(conversions) {
  const mapping = {};
  
  conversions.forEach(conversion => {
    if (conversion) {
      mapping[conversion.originalPath] = conversion.webpPath;
    }
  });
  
  fs.writeFileSync(
    path.join(__dirname, '../src/lib/image-mappings.json'),
    JSON.stringify(mapping, null, 2)
  );
  
  console.log('Generated image mapping file at src/lib/image-mappings.json');
}

// Generate TypeScript utility for accessing WebP images
function generateTsHelper() {
  const helperContent = `// Auto-generated utility for accessing WebP images
// This file is auto-generated by the convert-images script. Do not edit manually.

import imageMappings from './image-mappings.json';

/**
 * Gets the WebP version of an image path
 * @param originalPath The original image path (jpg, png)
 * @returns The WebP image path or the original if no WebP conversion exists
 */
export function getWebPPath(originalPath: string): string {
  // Handle paths with or without leading slash
  const normalizedPath = originalPath.startsWith('/')
    ? originalPath.substring(1)
    : originalPath;
  
  return (imageMappings as Record<string, string>)[normalizedPath] || originalPath;
}`;
  
  fs.writeFileSync(
    path.join(__dirname, '../src/lib/webp-helper.ts'),
    helperContent
  );
  
  console.log('Generated TypeScript helper at src/lib/webp-helper.ts');
}

// Main function
async function main() {
  console.log('Starting image conversion to WebP...');
  
  try {
    // Find all images
    const imageFiles = await findImages();
    console.log(`Found ${imageFiles.length} images to process`);
    
    // Convert all images to WebP
    const conversions = await Promise.all(imageFiles.map(convertImage));
    
    // Generate helper files
    generateMappingFile(conversions.filter(Boolean));
    generateTsHelper();
    
    console.log('Image conversion complete!');
  } catch (err) {
    console.error('Conversion failed:', err);
  }
}

main(); 